sudo: required
dist: jammy
language: node_js
node_js:
  - '14.20.1'
addons:
  chrome: stable

services:
  - xvfb

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0

install:
  - npm install -g makeshift && makeshift -s @systelab-technologies -r https://registry.npmjs.org
  - npm ci

script:
  - npm run build-lib
  - npm run build-showcase

after_success: |
  if [ -n "$GITHUB_API_KEY" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    git clone https://github.com/systelab/systelab.github.io.git
    rm -rf systelab.github.io/charts/*
    cp -r dist/showcase/* systelab.github.io/charts
    sed -i -e "s~base href=\"/\"~base href=\"/charts/\"~g" ./systelab.github.io/charts/index.html
    cd systelab.github.io
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m 'New deploy from Travis'
    git push -f -q https://systelab:$GITHUB_API_KEY@github.com/systelab/systelab.github.io
    cd ..
  fi

before_deploy:
  - cd dist/systelab-meters

deploy:
  provider: npm
  email: aserra@werfen.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
