sudo: required
dist: jammy
language: node_js
node_js:
  - '14.20.1'
addons:
  chrome: stable

services:
  - xvfb

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0

install:
  - npm install -g makeshift && makeshift -s @systelab-technologies -r https://registry.npmjs.org
  - npm ci

script:
  - npm run build-lib
  - npm run build-showcase


before_deploy:
  - cd dist/systelab-meters

deploy:
  provider: npm
  email: aserra@werfen.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
